# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Interface.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QLabel, QMainWindow, QPushButton, QSizePolicy,
    QSpinBox, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(796, 592)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.comboBox_Port = QComboBox(self.centralwidget)
        self.comboBox_Port.setObjectName(u"comboBox_Port")
        self.comboBox_Port.setGeometry(QRect(9, 9, 80, 24))
        self.pushButton_Serial_Connect = QPushButton(self.centralwidget)
        self.pushButton_Serial_Connect.setObjectName(u"pushButton_Serial_Connect")
        self.pushButton_Serial_Connect.setGeometry(QRect(110, 10, 75, 24))
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(20, 60, 651, 501))
        self.gridLayout_2 = QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_Channel_CH_1 = QFrame(self.widget)
        self.frame_Channel_CH_1.setObjectName(u"frame_Channel_CH_1")
        self.frame_Channel_CH_1.setEnabled(False)
        self.frame_Channel_CH_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_1.setFrameShadow(QFrame.Shadow.Raised)
        self.label = QLabel(self.frame_Channel_CH_1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 5, 61, 16))
        self.label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_1 = QPushButton(self.frame_Channel_CH_1)
        self.pushButton_State_CH_1.setObjectName(u"pushButton_State_CH_1")
        self.pushButton_State_CH_1.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_1 = QSpinBox(self.frame_Channel_CH_1)
        self.spinBox_Duty_CH_1.setObjectName(u"spinBox_Duty_CH_1")
        self.spinBox_Duty_CH_1.setEnabled(False)
        self.spinBox_Duty_CH_1.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_1.setMaximum(4095)
        self.label_2 = QLabel(self.frame_Channel_CH_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 5, 111, 16))
        self.label_3 = QLabel(self.frame_Channel_CH_1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_1 = QLabel(self.frame_Channel_CH_1)
        self.label_Voltage_CH_1.setObjectName(u"label_Voltage_CH_1")
        self.label_Voltage_CH_1.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_1 = QPushButton(self.frame_Channel_CH_1)
        self.pushButton_Set_CH_1.setObjectName(u"pushButton_Set_CH_1")
        self.pushButton_Set_CH_1.setEnabled(False)
        self.pushButton_Set_CH_1.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_1 = QPushButton(self.frame_Channel_CH_1)
        self.pushButton_LiveState_CH_1.setObjectName(u"pushButton_LiveState_CH_1")
        self.pushButton_LiveState_CH_1.setEnabled(False)
        self.pushButton_LiveState_CH_1.setGeometry(QRect(5, 65, 61, 22))
        self.label_4 = QLabel(self.frame_Channel_CH_1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_1 = QLabel(self.frame_Channel_CH_1)
        self.label_Current_Voltage_CH_1.setObjectName(u"label_Current_Voltage_CH_1")
        self.label_Current_Voltage_CH_1.setGeometry(QRect(210, 70, 49, 16))
        self.label_5 = QLabel(self.frame_Channel_CH_1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_1 = QLabel(self.frame_Channel_CH_1)
        self.label_Current_Duty_CH_1.setObjectName(u"label_Current_Duty_CH_1")
        self.label_Current_Duty_CH_1.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_1, 0, 0, 1, 1)

        self.frame_Channel_CH_5 = QFrame(self.widget)
        self.frame_Channel_CH_5.setObjectName(u"frame_Channel_CH_5")
        self.frame_Channel_CH_5.setEnabled(False)
        self.frame_Channel_CH_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_5.setFrameShadow(QFrame.Shadow.Raised)
        self.label_21 = QLabel(self.frame_Channel_CH_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 5, 61, 16))
        self.label_21.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_5 = QPushButton(self.frame_Channel_CH_5)
        self.pushButton_State_CH_5.setObjectName(u"pushButton_State_CH_5")
        self.pushButton_State_CH_5.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_5 = QSpinBox(self.frame_Channel_CH_5)
        self.spinBox_Duty_CH_5.setObjectName(u"spinBox_Duty_CH_5")
        self.spinBox_Duty_CH_5.setEnabled(False)
        self.spinBox_Duty_CH_5.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_5.setMaximum(4095)
        self.label_22 = QLabel(self.frame_Channel_CH_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(80, 5, 111, 16))
        self.label_23 = QLabel(self.frame_Channel_CH_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_5 = QLabel(self.frame_Channel_CH_5)
        self.label_Voltage_CH_5.setObjectName(u"label_Voltage_CH_5")
        self.label_Voltage_CH_5.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_5 = QPushButton(self.frame_Channel_CH_5)
        self.pushButton_Set_CH_5.setObjectName(u"pushButton_Set_CH_5")
        self.pushButton_Set_CH_5.setEnabled(False)
        self.pushButton_Set_CH_5.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_5 = QPushButton(self.frame_Channel_CH_5)
        self.pushButton_LiveState_CH_5.setObjectName(u"pushButton_LiveState_CH_5")
        self.pushButton_LiveState_CH_5.setEnabled(False)
        self.pushButton_LiveState_CH_5.setGeometry(QRect(5, 65, 61, 22))
        self.label_24 = QLabel(self.frame_Channel_CH_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_5 = QLabel(self.frame_Channel_CH_5)
        self.label_Current_Voltage_CH_5.setObjectName(u"label_Current_Voltage_CH_5")
        self.label_Current_Voltage_CH_5.setGeometry(QRect(210, 70, 49, 16))
        self.label_25 = QLabel(self.frame_Channel_CH_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_5 = QLabel(self.frame_Channel_CH_5)
        self.label_Current_Duty_CH_5.setObjectName(u"label_Current_Duty_CH_5")
        self.label_Current_Duty_CH_5.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_5, 0, 1, 1, 1)

        self.frame_Channel_CH_2 = QFrame(self.widget)
        self.frame_Channel_CH_2.setObjectName(u"frame_Channel_CH_2")
        self.frame_Channel_CH_2.setEnabled(False)
        self.frame_Channel_CH_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_2.setFrameShadow(QFrame.Shadow.Raised)
        self.label_6 = QLabel(self.frame_Channel_CH_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 5, 61, 16))
        self.label_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_2 = QPushButton(self.frame_Channel_CH_2)
        self.pushButton_State_CH_2.setObjectName(u"pushButton_State_CH_2")
        self.pushButton_State_CH_2.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_2 = QSpinBox(self.frame_Channel_CH_2)
        self.spinBox_Duty_CH_2.setObjectName(u"spinBox_Duty_CH_2")
        self.spinBox_Duty_CH_2.setEnabled(False)
        self.spinBox_Duty_CH_2.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_2.setMaximum(4095)
        self.label_7 = QLabel(self.frame_Channel_CH_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 5, 111, 16))
        self.label_8 = QLabel(self.frame_Channel_CH_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_2 = QLabel(self.frame_Channel_CH_2)
        self.label_Voltage_CH_2.setObjectName(u"label_Voltage_CH_2")
        self.label_Voltage_CH_2.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_2 = QPushButton(self.frame_Channel_CH_2)
        self.pushButton_Set_CH_2.setObjectName(u"pushButton_Set_CH_2")
        self.pushButton_Set_CH_2.setEnabled(False)
        self.pushButton_Set_CH_2.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_2 = QPushButton(self.frame_Channel_CH_2)
        self.pushButton_LiveState_CH_2.setObjectName(u"pushButton_LiveState_CH_2")
        self.pushButton_LiveState_CH_2.setEnabled(False)
        self.pushButton_LiveState_CH_2.setGeometry(QRect(5, 65, 61, 22))
        self.label_9 = QLabel(self.frame_Channel_CH_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_2 = QLabel(self.frame_Channel_CH_2)
        self.label_Current_Voltage_CH_2.setObjectName(u"label_Current_Voltage_CH_2")
        self.label_Current_Voltage_CH_2.setGeometry(QRect(210, 70, 49, 16))
        self.label_10 = QLabel(self.frame_Channel_CH_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_2 = QLabel(self.frame_Channel_CH_2)
        self.label_Current_Duty_CH_2.setObjectName(u"label_Current_Duty_CH_2")
        self.label_Current_Duty_CH_2.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_2, 1, 0, 1, 1)

        self.frame_Channel_CH_6 = QFrame(self.widget)
        self.frame_Channel_CH_6.setObjectName(u"frame_Channel_CH_6")
        self.frame_Channel_CH_6.setEnabled(False)
        self.frame_Channel_CH_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_6.setFrameShadow(QFrame.Shadow.Raised)
        self.label_26 = QLabel(self.frame_Channel_CH_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 5, 61, 16))
        self.label_26.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_6 = QPushButton(self.frame_Channel_CH_6)
        self.pushButton_State_CH_6.setObjectName(u"pushButton_State_CH_6")
        self.pushButton_State_CH_6.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_6 = QSpinBox(self.frame_Channel_CH_6)
        self.spinBox_Duty_CH_6.setObjectName(u"spinBox_Duty_CH_6")
        self.spinBox_Duty_CH_6.setEnabled(False)
        self.spinBox_Duty_CH_6.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_6.setMaximum(4095)
        self.label_27 = QLabel(self.frame_Channel_CH_6)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(80, 5, 111, 16))
        self.label_28 = QLabel(self.frame_Channel_CH_6)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_6 = QLabel(self.frame_Channel_CH_6)
        self.label_Voltage_CH_6.setObjectName(u"label_Voltage_CH_6")
        self.label_Voltage_CH_6.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_6 = QPushButton(self.frame_Channel_CH_6)
        self.pushButton_Set_CH_6.setObjectName(u"pushButton_Set_CH_6")
        self.pushButton_Set_CH_6.setEnabled(False)
        self.pushButton_Set_CH_6.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_6 = QPushButton(self.frame_Channel_CH_6)
        self.pushButton_LiveState_CH_6.setObjectName(u"pushButton_LiveState_CH_6")
        self.pushButton_LiveState_CH_6.setEnabled(False)
        self.pushButton_LiveState_CH_6.setGeometry(QRect(5, 65, 61, 22))
        self.label_29 = QLabel(self.frame_Channel_CH_6)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_6 = QLabel(self.frame_Channel_CH_6)
        self.label_Current_Voltage_CH_6.setObjectName(u"label_Current_Voltage_CH_6")
        self.label_Current_Voltage_CH_6.setGeometry(QRect(210, 70, 49, 16))
        self.label_30 = QLabel(self.frame_Channel_CH_6)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_6 = QLabel(self.frame_Channel_CH_6)
        self.label_Current_Duty_CH_6.setObjectName(u"label_Current_Duty_CH_6")
        self.label_Current_Duty_CH_6.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_6, 1, 1, 1, 1)

        self.frame_Channel_CH_3 = QFrame(self.widget)
        self.frame_Channel_CH_3.setObjectName(u"frame_Channel_CH_3")
        self.frame_Channel_CH_3.setEnabled(False)
        self.frame_Channel_CH_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_3.setFrameShadow(QFrame.Shadow.Raised)
        self.label_11 = QLabel(self.frame_Channel_CH_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 5, 61, 16))
        self.label_11.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_3 = QPushButton(self.frame_Channel_CH_3)
        self.pushButton_State_CH_3.setObjectName(u"pushButton_State_CH_3")
        self.pushButton_State_CH_3.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_3 = QSpinBox(self.frame_Channel_CH_3)
        self.spinBox_Duty_CH_3.setObjectName(u"spinBox_Duty_CH_3")
        self.spinBox_Duty_CH_3.setEnabled(False)
        self.spinBox_Duty_CH_3.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_3.setMaximum(4095)
        self.label_12 = QLabel(self.frame_Channel_CH_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(80, 5, 111, 16))
        self.label_13 = QLabel(self.frame_Channel_CH_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_3 = QLabel(self.frame_Channel_CH_3)
        self.label_Voltage_CH_3.setObjectName(u"label_Voltage_CH_3")
        self.label_Voltage_CH_3.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_3 = QPushButton(self.frame_Channel_CH_3)
        self.pushButton_Set_CH_3.setObjectName(u"pushButton_Set_CH_3")
        self.pushButton_Set_CH_3.setEnabled(False)
        self.pushButton_Set_CH_3.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_3 = QPushButton(self.frame_Channel_CH_3)
        self.pushButton_LiveState_CH_3.setObjectName(u"pushButton_LiveState_CH_3")
        self.pushButton_LiveState_CH_3.setEnabled(False)
        self.pushButton_LiveState_CH_3.setGeometry(QRect(5, 65, 61, 22))
        self.label_14 = QLabel(self.frame_Channel_CH_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_3 = QLabel(self.frame_Channel_CH_3)
        self.label_Current_Voltage_CH_3.setObjectName(u"label_Current_Voltage_CH_3")
        self.label_Current_Voltage_CH_3.setGeometry(QRect(210, 70, 49, 16))
        self.label_15 = QLabel(self.frame_Channel_CH_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_3 = QLabel(self.frame_Channel_CH_3)
        self.label_Current_Duty_CH_3.setObjectName(u"label_Current_Duty_CH_3")
        self.label_Current_Duty_CH_3.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_3, 2, 0, 1, 1)

        self.frame_Channel_CH_7 = QFrame(self.widget)
        self.frame_Channel_CH_7.setObjectName(u"frame_Channel_CH_7")
        self.frame_Channel_CH_7.setEnabled(False)
        self.frame_Channel_CH_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_7.setFrameShadow(QFrame.Shadow.Raised)
        self.label_31 = QLabel(self.frame_Channel_CH_7)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 5, 61, 16))
        self.label_31.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_7 = QPushButton(self.frame_Channel_CH_7)
        self.pushButton_State_CH_7.setObjectName(u"pushButton_State_CH_7")
        self.pushButton_State_CH_7.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_7 = QSpinBox(self.frame_Channel_CH_7)
        self.spinBox_Duty_CH_7.setObjectName(u"spinBox_Duty_CH_7")
        self.spinBox_Duty_CH_7.setEnabled(False)
        self.spinBox_Duty_CH_7.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_7.setMaximum(4095)
        self.label_32 = QLabel(self.frame_Channel_CH_7)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(80, 5, 111, 16))
        self.label_33 = QLabel(self.frame_Channel_CH_7)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_7 = QLabel(self.frame_Channel_CH_7)
        self.label_Voltage_CH_7.setObjectName(u"label_Voltage_CH_7")
        self.label_Voltage_CH_7.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_7 = QPushButton(self.frame_Channel_CH_7)
        self.pushButton_Set_CH_7.setObjectName(u"pushButton_Set_CH_7")
        self.pushButton_Set_CH_7.setEnabled(False)
        self.pushButton_Set_CH_7.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_7 = QPushButton(self.frame_Channel_CH_7)
        self.pushButton_LiveState_CH_7.setObjectName(u"pushButton_LiveState_CH_7")
        self.pushButton_LiveState_CH_7.setEnabled(False)
        self.pushButton_LiveState_CH_7.setGeometry(QRect(5, 65, 61, 22))
        self.label_34 = QLabel(self.frame_Channel_CH_7)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_7 = QLabel(self.frame_Channel_CH_7)
        self.label_Current_Voltage_CH_7.setObjectName(u"label_Current_Voltage_CH_7")
        self.label_Current_Voltage_CH_7.setGeometry(QRect(210, 70, 49, 16))
        self.label_35 = QLabel(self.frame_Channel_CH_7)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_7 = QLabel(self.frame_Channel_CH_7)
        self.label_Current_Duty_CH_7.setObjectName(u"label_Current_Duty_CH_7")
        self.label_Current_Duty_CH_7.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_7, 2, 1, 1, 1)

        self.frame_Channel_CH_4 = QFrame(self.widget)
        self.frame_Channel_CH_4.setObjectName(u"frame_Channel_CH_4")
        self.frame_Channel_CH_4.setEnabled(False)
        self.frame_Channel_CH_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_4.setFrameShadow(QFrame.Shadow.Raised)
        self.label_16 = QLabel(self.frame_Channel_CH_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 5, 61, 16))
        self.label_16.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_4 = QPushButton(self.frame_Channel_CH_4)
        self.pushButton_State_CH_4.setObjectName(u"pushButton_State_CH_4")
        self.pushButton_State_CH_4.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_4 = QSpinBox(self.frame_Channel_CH_4)
        self.spinBox_Duty_CH_4.setObjectName(u"spinBox_Duty_CH_4")
        self.spinBox_Duty_CH_4.setEnabled(False)
        self.spinBox_Duty_CH_4.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_4.setMaximum(4095)
        self.label_17 = QLabel(self.frame_Channel_CH_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(80, 5, 111, 16))
        self.label_18 = QLabel(self.frame_Channel_CH_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_4 = QLabel(self.frame_Channel_CH_4)
        self.label_Voltage_CH_4.setObjectName(u"label_Voltage_CH_4")
        self.label_Voltage_CH_4.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_4 = QPushButton(self.frame_Channel_CH_4)
        self.pushButton_Set_CH_4.setObjectName(u"pushButton_Set_CH_4")
        self.pushButton_Set_CH_4.setEnabled(False)
        self.pushButton_Set_CH_4.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_4 = QPushButton(self.frame_Channel_CH_4)
        self.pushButton_LiveState_CH_4.setObjectName(u"pushButton_LiveState_CH_4")
        self.pushButton_LiveState_CH_4.setEnabled(False)
        self.pushButton_LiveState_CH_4.setGeometry(QRect(5, 65, 61, 22))
        self.label_19 = QLabel(self.frame_Channel_CH_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_4 = QLabel(self.frame_Channel_CH_4)
        self.label_Current_Voltage_CH_4.setObjectName(u"label_Current_Voltage_CH_4")
        self.label_Current_Voltage_CH_4.setGeometry(QRect(210, 70, 49, 16))
        self.label_20 = QLabel(self.frame_Channel_CH_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_4 = QLabel(self.frame_Channel_CH_4)
        self.label_Current_Duty_CH_4.setObjectName(u"label_Current_Duty_CH_4")
        self.label_Current_Duty_CH_4.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_4, 3, 0, 1, 1)

        self.frame_Channel_CH_8 = QFrame(self.widget)
        self.frame_Channel_CH_8.setObjectName(u"frame_Channel_CH_8")
        self.frame_Channel_CH_8.setEnabled(False)
        self.frame_Channel_CH_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Channel_CH_8.setFrameShadow(QFrame.Shadow.Raised)
        self.label_36 = QLabel(self.frame_Channel_CH_8)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 5, 61, 16))
        self.label_36.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_State_CH_8 = QPushButton(self.frame_Channel_CH_8)
        self.pushButton_State_CH_8.setObjectName(u"pushButton_State_CH_8")
        self.pushButton_State_CH_8.setGeometry(QRect(5, 20, 61, 22))
        self.spinBox_Duty_CH_8 = QSpinBox(self.frame_Channel_CH_8)
        self.spinBox_Duty_CH_8.setObjectName(u"spinBox_Duty_CH_8")
        self.spinBox_Duty_CH_8.setEnabled(False)
        self.spinBox_Duty_CH_8.setGeometry(QRect(75, 20, 101, 28))
        self.spinBox_Duty_CH_8.setMaximum(4095)
        self.label_37 = QLabel(self.frame_Channel_CH_8)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(80, 5, 111, 16))
        self.label_38 = QLabel(self.frame_Channel_CH_8)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(80, 50, 101, 16))
        self.label_Voltage_CH_8 = QLabel(self.frame_Channel_CH_8)
        self.label_Voltage_CH_8.setObjectName(u"label_Voltage_CH_8")
        self.label_Voltage_CH_8.setGeometry(QRect(80, 70, 49, 16))
        self.pushButton_Set_CH_8 = QPushButton(self.frame_Channel_CH_8)
        self.pushButton_Set_CH_8.setObjectName(u"pushButton_Set_CH_8")
        self.pushButton_Set_CH_8.setEnabled(False)
        self.pushButton_Set_CH_8.setGeometry(QRect(5, 42, 61, 22))
        self.pushButton_LiveState_CH_8 = QPushButton(self.frame_Channel_CH_8)
        self.pushButton_LiveState_CH_8.setObjectName(u"pushButton_LiveState_CH_8")
        self.pushButton_LiveState_CH_8.setEnabled(False)
        self.pushButton_LiveState_CH_8.setGeometry(QRect(5, 65, 61, 22))
        self.label_39 = QLabel(self.frame_Channel_CH_8)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(210, 50, 71, 16))
        self.label_Current_Voltage_CH_8 = QLabel(self.frame_Channel_CH_8)
        self.label_Current_Voltage_CH_8.setObjectName(u"label_Current_Voltage_CH_8")
        self.label_Current_Voltage_CH_8.setGeometry(QRect(210, 70, 49, 16))
        self.label_40 = QLabel(self.frame_Channel_CH_8)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(210, 5, 81, 16))
        self.label_Current_Duty_CH_8 = QLabel(self.frame_Channel_CH_8)
        self.label_Current_Duty_CH_8.setObjectName(u"label_Current_Duty_CH_8")
        self.label_Current_Duty_CH_8.setGeometry(QRect(210, 25, 49, 16))

        self.gridLayout_2.addWidget(self.frame_Channel_CH_8, 3, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_Serial_Connect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Channel 1:", None))
        self.pushButton_State_CH_1.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_1.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_1.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Channel 5:", None))
        self.pushButton_State_CH_5.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_5.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_5.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Channel 2:", None))
        self.pushButton_State_CH_2.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_2.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_2.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Channel 6:", None))
        self.pushButton_State_CH_6.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_6.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_6.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Channel 3:", None))
        self.pushButton_State_CH_3.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_3.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_3.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Channel 7:", None))
        self.pushButton_State_CH_7.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_7.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_7.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Channel 4:", None))
        self.pushButton_State_CH_4.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_4.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_4.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Channel 8:", None))
        self.pushButton_State_CH_8.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Mem Duty :", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Mem Tension (V):", None))
        self.label_Voltage_CH_8.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_Set_CH_8.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.pushButton_LiveState_CH_8.setText(QCoreApplication.translate("MainWindow", u"Live on", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Tension (V):", None))
        self.label_Current_Voltage_CH_8.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Duty (0-4095):", None))
        self.label_Current_Duty_CH_8.setText(QCoreApplication.translate("MainWindow", u"0", None))
    # retranslateUi

